version: "3.8"

networks:
  shopswift-network:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx-shopswift
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - shopswift-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-shopswift
    restart: always
    volumes:
      - .:/var/www
    working_dir: /var/www
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - shopswift-network

  mysql:
    image: mysql:8.0
    container_name: mysql-shopswift
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vivieniedatn2026
      MYSQL_DATABASE: shopswift
      MYSQL_USER: shopswift
      MYSQL_PASSWORD: vivieniedatn2026
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - shopswift-network

volumes:
  mysql_data: